### PR TITLE
Add Data to my data base

### PR DESCRIPTION
**Pull request by nimplay**
- [ ] Create New data base Called "vet_clinic"
- [ ] create new table called Animals
- [ ] adding data to table
- [ ] conulting data Using SQL commands
- [ ] clone "curriculum-databases-projects-template"
- [ ] add data uinto the three files
Captura de pantalla 2022-09-12 a la(s) 2 53 53 p  m
Captura de pantalla 2022-09-12 a la(s) 2 53 29 p  m
Captura de pantalla 2022-09-12 a la(s) 2 53 03 p  m
Captura de pantalla 2022-09-12 a la(s) 2 49 38 p  m
Captura de pantalla 2022-09-12 a la(s) 2 50 39 p  m
Captura de pantalla 2022-09-12 a la(s) 2 51 29 p  m
Captura de pantalla 2022-09-12 a la(s) 2 51 58 p  m
Captura de pantalla 2022-09-12 a la(s) 2 52 31 p  m

### CODE REVIEW

**Review by tufoinnkuo10 — CHANGES_REQUESTED** [review]
Hi @nimplay 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message

Required Changes ♻️

- [ Required] Please add screenshots of the query results to the pull request description, This will help to ensure that you ran the queries with success.

- [optional] please always wait for a pull request to be approved by a CR before you merge. i could not find all your files.
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by nimplay** [comment]
Add Query screenshots Done!!

**Comment by ShadyShawkat** [comment]
## Hi @nimplay, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

Image

 ## Required Changes ♻️
- [ ] Please add the screenshots of you running each query to the _**pull request's description**_, not as an image inside the project's files as instructed by the previous reviewer. You can read the project's requirement that requires this from [here](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_create_tables.md#:~:text=Remember%20to%20add%20the%20screenshot%20with%20the%20results%20of%20your%20queries%20to%20your%20Pull%20Request%20description.).

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by nicupop729 — COMMENTED** [review]
Hello @nimplay  👋,

_This is an additional review as a result of the second opinion request._

Kudos for the excellent work you have done here!

Regarding your Second Opinion request, I must state the following:
- Both reviewers mentioned that you didn't follow the project requirements regarding that you need to add the screenshot with the results of your queries to your Pull Request description, and not in the repo, as you did.

Screenshot from the project requirements:
image

As the project requirements clearly state, please add the screenshot with the result of your queries to your Pull Request description and if you will do so, the next reviewer will be more than happy to approve your CRR.

Keep rocking 🚀!

**Comment by nimplay** [comment]
Add a screenshot for each query
Captura de pantalla 2022-09-12 a la(s) 2 52 31 p  m
Captura de pantalla 2022-09-12 a la(s) 2 51 58 p  m
Captura de pantalla 2022-09-12 a la(s) 2 51 29 p  m
Captura de pantalla 2022-09-12 a la(s) 2 50 39 p  m
Captura de pantalla 2022-09-12 a la(s) 2 49 38 p  m

Captura de pantalla 2022-09-12 a la(s) 2 53 53 p  m
Captura de pantalla 2022-09-12 a la(s) 2 53 29 p  m
Captura de pantalla 2022-09-12 a la(s) 2 53 03 p  m

**Review by mukhammadrizooff — APPROVED** [review]
Hi @nimplay, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
- Good implementations ✔️ 
- Give the correct value ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
